version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "08:00"
      timezone: "Europe/London"
    ignore:
      - dependency-name: "bootstrap"
        versions: ["5.3.3"]
