blank_issues_enabled: true
contact_links:
  - name: Contact us
    url: https://rasperrevision.github.io/contact/
    about: Any questions can be asked on our contact page. Anything else can be reported with the links above.
