blank_issues_enabled: true
contact_links:
  - name: Contact us
    url: https://rasperrevision.github.io/contact/
    about: Any questions can be asked on our contact page.
  - name: Security advisories
    url: https://github.com/RasperRevision/RasperRevision.github.io/security
    about: Any security vulnerabilities can be privately reported in the Github security tab
